version: 0.0
os: linux
files:
  - source: /app.zip
    destination: /var/www/myapp
hooks:
  BeforeInstall:
    - location: scripts/codedeploy_dependencies.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/deploy.sh
      timeout: 300
      runas: root
